/* tslint:disable */
/* eslint-disable */
/**
 * iTunes Search API
 * API for searching iTunes content
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { Itunes } from "../models/index";
import { ItunesFromJSON, ItunesToJSON } from "../models/index";

export interface GetItunesRequest {
	term?: string;
	limit?: number;
}

/**
 *
 */
export class ItunesApi extends runtime.BaseAPI {
	/**
	 * Get and Search for movies, music, and other content in the iTunes store
	 * Get and Search iTunes content
	 */
	async getItunesRaw(
		requestParameters: GetItunesRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<Itunes>> {
		const queryParameters: any = {};

		if (requestParameters["term"] != null) {
			queryParameters["term"] = requestParameters["term"];
		}

		if (requestParameters["limit"] != null) {
			queryParameters["limit"] = requestParameters["limit"];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/itunes`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			ItunesFromJSON(jsonValue),
		);
	}

	/**
	 * Get and Search for movies, music, and other content in the iTunes store
	 * Get and Search iTunes content
	 */
	async getItunes(
		requestParameters: GetItunesRequest = {},
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<Itunes> {
		const response = await this.getItunesRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
