/* tslint:disable */
/* eslint-disable */
/**
 * iTunes Search API
 * API for searching iTunes content
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Track } from './Track';
import {
    TrackFromJSON,
    TrackFromJSONTyped,
    TrackToJSON,
    TrackToJSONTyped,
} from './Track';

/**
 * 
 * @export
 * @interface Itunes
 */
export interface Itunes {
    /**
     * 
     * @type {number}
     * @memberof Itunes
     */
    resultCount?: number;
    /**
     * 
     * @type {Array<Track>}
     * @memberof Itunes
     */
    results?: Array<Track>;
}

/**
 * Check if a given object implements the Itunes interface.
 */
export function instanceOfItunes(value: object): value is Itunes {
    return true;
}

export function ItunesFromJSON(json: any): Itunes {
    return ItunesFromJSONTyped(json, false);
}

export function ItunesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Itunes {
    if (json == null) {
        return json;
    }
    return {
        
        'resultCount': json['resultCount'] == null ? undefined : json['resultCount'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(TrackFromJSON)),
    };
}

export function ItunesToJSON(json: any): Itunes {
    return ItunesToJSONTyped(json, false);
}

export function ItunesToJSONTyped(value?: Itunes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resultCount': value['resultCount'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(TrackToJSON)),
    };
}

