/* tslint:disable */
/* eslint-disable */
/**
 * iTunes Search API
 * API for searching iTunes content
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Track
 */
export interface Track {
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	wrapperType?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	kind?: string;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	artistId?: number;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	trackId?: number;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	collectionId?: number;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	collectionName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	collectionCensoredName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	collectionViewUrl?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	artistName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	trackName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	trackCensoredName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	trackViewUrl?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	previewUrl?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	artworkUrl30?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	artworkUrl60?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	artworkUrl100?: string;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	collectionPrice?: number;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	trackPrice?: number;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	trackRentalPrice?: number;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	collectionHdPrice?: number;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	trackHdPrice?: number;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	trackHdRentalPrice?: number;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	releaseDate?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	collectionExplicitness?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	trackExplicitness?: string;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	trackTimeMillis?: number;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	country?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	currency?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	primaryGenreName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	contentAdvisoryRating?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	shortDescription?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Track
	 */
	longDescription?: string;
	/**
	 *
	 * @type {number}
	 * @memberof Track
	 */
	collectionId?: number;
}

/**
 * Check if a given object implements the Track interface.
 */
export function instanceOfTrack(value: object): value is Track {
	return true;
}

export function TrackFromJSON(json: any): Track {
	return TrackFromJSONTyped(json, false);
}

export function TrackFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): Track {
	if (json == null) {
		return json;
	}
	return {
		wrapperType: json["wrapperType"] == null ? undefined : json["wrapperType"],
		kind: json["kind"] == null ? undefined : json["kind"],
		artistId: json["artistId"] == null ? undefined : json["artistId"],
		trackId: json["trackId"] == null ? undefined : json["trackId"],
		artistName: json["artistName"] == null ? undefined : json["artistName"],
		trackName: json["trackName"] == null ? undefined : json["trackName"],
		trackCensoredName:
			json["trackCensoredName"] == null ? undefined : json["trackCensoredName"],
		trackViewUrl:
			json["trackViewUrl"] == null ? undefined : json["trackViewUrl"],
		previewUrl: json["previewUrl"] == null ? undefined : json["previewUrl"],
		artworkUrl30:
			json["artworkUrl30"] == null ? undefined : json["artworkUrl30"],
		artworkUrl60:
			json["artworkUrl60"] == null ? undefined : json["artworkUrl60"],
		artworkUrl100:
			json["artworkUrl100"] == null ? undefined : json["artworkUrl100"],
		collectionPrice:
			json["collectionPrice"] == null ? undefined : json["collectionPrice"],
		trackPrice: json["trackPrice"] == null ? undefined : json["trackPrice"],
		trackRentalPrice:
			json["trackRentalPrice"] == null ? undefined : json["trackRentalPrice"],
		collectionHdPrice:
			json["collectionHdPrice"] == null ? undefined : json["collectionHdPrice"],
		trackHdPrice:
			json["trackHdPrice"] == null ? undefined : json["trackHdPrice"],
		trackHdRentalPrice:
			json["trackHdRentalPrice"] == null
				? undefined
				: json["trackHdRentalPrice"],
		releaseDate: json["releaseDate"] == null ? undefined : json["releaseDate"],
		collectionExplicitness:
			json["collectionExplicitness"] == null
				? undefined
				: json["collectionExplicitness"],
		trackExplicitness:
			json["trackExplicitness"] == null ? undefined : json["trackExplicitness"],
		trackTimeMillis:
			json["trackTimeMillis"] == null ? undefined : json["trackTimeMillis"],
		country: json["country"] == null ? undefined : json["country"],
		currency: json["currency"] == null ? undefined : json["currency"],
		primaryGenreName:
			json["primaryGenreName"] == null ? undefined : json["primaryGenreName"],
		contentAdvisoryRating:
			json["contentAdvisoryRating"] == null
				? undefined
				: json["contentAdvisoryRating"],
		shortDescription:
			json["shortDescription"] == null ? undefined : json["shortDescription"],
		longDescription:
			json["longDescription"] == null ? undefined : json["longDescription"],
		collectionId:
			json["collectionId"] == null ? undefined : json["collectionId"],
	};
}

export function TrackToJSON(json: any): Track {
	return TrackToJSONTyped(json, false);
}

export function TrackToJSONTyped(
	value?: Track | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		wrapperType: value["wrapperType"],
		kind: value["kind"],
		artistId: value["artistId"],
		trackId: value["trackId"],
		artistName: value["artistName"],
		trackName: value["trackName"],
		trackCensoredName: value["trackCensoredName"],
		trackViewUrl: value["trackViewUrl"],
		previewUrl: value["previewUrl"],
		artworkUrl30: value["artworkUrl30"],
		artworkUrl60: value["artworkUrl60"],
		artworkUrl100: value["artworkUrl100"],
		collectionPrice: value["collectionPrice"],
		trackPrice: value["trackPrice"],
		trackRentalPrice: value["trackRentalPrice"],
		collectionHdPrice: value["collectionHdPrice"],
		trackHdPrice: value["trackHdPrice"],
		trackHdRentalPrice: value["trackHdRentalPrice"],
		releaseDate: value["releaseDate"],
		collectionExplicitness: value["collectionExplicitness"],
		trackExplicitness: value["trackExplicitness"],
		trackTimeMillis: value["trackTimeMillis"],
		country: value["country"],
		currency: value["currency"],
		primaryGenreName: value["primaryGenreName"],
		contentAdvisoryRating: value["contentAdvisoryRating"],
		shortDescription: value["shortDescription"],
		longDescription: value["longDescription"],
		collectionId: value["collectionId"],
	};
}
